apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kiali.name" . }}
    helm.sh/chart: {{ template "kiali.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    server:
      port: 20001
    external_services:
      jaeger:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}
