apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kiali.name" . }}
    helm.sh/chart: {{ template "kiali.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
  - name: http-kiali
    protocol: TCP
    port: 20001
  selector:
    app.kubernetes.io/name: kiali
