apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-istiocoredns-role-binding-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "istiocoredns.name" . }}
    helm.sh/chart: {{ template "istiocoredns.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istiocoredns
subjects:
- kind: ServiceAccount
  name: istiocoredns-service-account
  namespace: {{ .Release.Namespace }}
