apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiocoredns
  labels:
    app.kubernetes.io/name: {{ template "istiocoredns.name" . }}
    helm.sh/chart: {{ template "istiocoredns.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: ["networking.istio.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
