apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "istiocoredns.name" . }}
    helm.sh/chart: {{ template "istiocoredns.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  Corefile: |
    .:53 {
          errors
          health
          proxy global 127.0.0.1:8053 {
            protocol grpc insecure
          }
          prometheus :9153
          proxy . /etc/resolv.conf
          cache 30
          reload
        }
---
