apiVersion: v1
kind: Service
metadata:
  name: istiocoredns
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "istiocoredns.name" . }}
    helm.sh/chart: {{ template "istiocoredns.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: istiocoredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
