apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: istio-ingress-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "ingress.name" . }}
    helm.sh/chart: {{ template "ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-pilot-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-ingress-service-account
    namespace: {{ .Release.Namespace }}
