{{- if or .Values.podDisruptionBudget .Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "ingress.name" . }}
    helm.sh/chart: {{ template "ingress.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: ingress
spec:
{{- if .Values.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
{{- else if .Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "ingress.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      istio: ingress
{{- end }}
