apiVersion: v1
kind: Service
metadata:
  name: tornado
  labels:
    app.kubernetes.io/name: tornado
spec:
  ports:
  - port: 8888
    name: http
  selector:
    app.kubernetes.io/name: tornado
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tornado
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tornado
        app.kubernetes.io/version: v1
    spec:
      containers:
      - name: tornado
        image: hiroakis/tornado-websocket-example
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
---
