{{- if .Values.global.meshExpansion.enabled }}
{{- if .Values.global.meshExpansion.useILB }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-citadel-ilb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "security.name" . }}
    helm.sh/chart: {{ template "security.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: citadel
spec:
  hosts:
  - istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
  gateways:
  - meshexpansion-ilb-gateway
  tcp:
  - match:
    - port: 8060
    route:
    - destination:
        host: istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
        port:
          number: 8060
---
{{- else }}

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-citadel
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "security.name" . }}
    helm.sh/chart: {{ template "security.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: citadel
spec:
  hosts:
  - istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
  gateways:
  - meshexpansion-gateway
  tcp:
  - match:
    - port: 8060
    route:
    - destination:
        host: istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
        port:
          number: 8060
---
{{- end }}
{{- end }}
