apiVersion: v1
kind: Service
metadata:
  name: servicegraph
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app.kubernetes.io/name: servicegraph
    helm.sh/chart: {{ template "servicegraph.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 8088
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: servicegraph
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
  {{if .Values.service.loadBalancerSourceRanges}}
  loadBalancerSourceRanges:
    {{range $rangeList := .Values.service.loadBalancerSourceRanges}}
    - {{ $rangeList }}
    {{end}}
  {{end}}