{{- if .Values.autoscaleMin }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-pilot
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "pilot.name" . }}
    helm.sh/chart: {{ template "pilot.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.autoscaleMax }}
  minReplicas: {{ .Values.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: istio-pilot
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.cpu.targetAverageUtilization }}
---
{{- end }}
