apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "pilot.name" . }}
    helm.sh/chart: {{ template "pilot.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 8080
    name: http-legacy-discovery # direct
  - port: {{ .Values.global.monitoringPort }}
    name: http-monitoring
  selector:
    istio: pilot
