apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana-custom-resources
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "grafana.name" . }}
    helm.sh/chart: {{ template "grafana.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: grafana
data:
  custom-resources.yaml: |-
    {{- include "grafana-default.yaml.tpl" . | indent 4}}
  run.sh: |-
    {{- include "install-custom-resources.sh.tpl" . | indent 4}}
