{{ define "grafana-default.yaml.tpl" }}
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: grafana-ports-mtls-disabled
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "grafana.name" . }}
    helm.sh/chart: {{ template "grafana.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  targets:
  - name: grafana
    ports:
    - number: {{ .Values.service.externalPort }}
{{- end }}
