{{- if .Values.persist }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: istio-grafana-pvc
  labels:
    app.kubernetes.io/name: {{ template "grafana.name" . }}
    helm.sh/chart: {{ template "grafana.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: 5Gi
{{- end }}
