apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-galley-configuration
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "galley.name" . }}
    helm.sh/chart: {{ template "galley.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: galley
data:
  validatingwebhookconfiguration.yaml: |-
    {{- include "validatingwebhookconfiguration.yaml.tpl" . | indent 4}}