apiVersion: v1
kind: Service
metadata:
  name: istio-galley
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "galley.name" . }}
    helm.sh/chart: {{ template "galley.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: galley
spec:
  ports:
  - port: 443
    name: https-validation
  - port: {{ .Values.global.monitoringPort }}
    name: http-monitoring
  - port: 9901
    name: grpc-mcp
  selector:
    istio: galley
