apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "sidecar-injector.name" . }}
    helm.sh/chart: {{ template "sidecar-injector.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    istio: sidecar-injector
spec:
  ports:
  - port: 443
  selector:
    istio: sidecar-injector
