apiVersion: v1
kind: Service
metadata:
  name: liveness-http
  labels:
    app.kubernetes.io/name: liveness-http
spec:
  ports:
  - name: http
    port: 8001
  selector:
    app.kubernetes.io/name: liveness-http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness-http
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: liveness-http
        app.kubernetes.io/version: v1
    spec:
      containers:
      - name: liveness-http
        image: docker.io/istio/health:example
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /foo
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
