{{- range $key, $spec := .Values }}
{{- if ne $key "enabled" }}
{{- if and $spec.enabled $spec.autoscaleMin }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $key }}
  namespace: {{ $spec.namespace | default $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $spec.labels.istio }}
    helm.sh/chart: {{ template "gateway.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  maxReplicas: {{ $spec.autoscaleMax }}
  minReplicas: {{ $spec.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ $key }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ $spec.cpu.targetAverageUtilization }}
---
{{- end }}
{{- end }}
{{- end }}
