{{- range $key, $spec := .Values }}
{{- if ne $key "enabled" }}
{{- if $spec.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ $key }}-{{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $spec.labels.istio }}
    helm.sh/chart: {{ template "gateway.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $key }}-{{ $.Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ $key }}-service-account
  namespace: {{ $.Release.Namespace }}
---
{{- end }}
{{- end }}
{{- end }}
