{{- range $key, $spec := .Values }}
{{- if and (ne $key "enabled") }}
{{- if $spec.enabled }}
{{- if or $spec.podDisruptionBudget $.Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $key }}
  namespace: {{ $spec.namespace | default $.Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "gateway.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- range $key, $val := $spec.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
{{- if $spec.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" $spec.podDisruptionBudget }}
{{- else if $.Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" $.Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      {{- range $key, $val := $spec.labels }}
      {{ $key }}: {{ $val }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
