apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: istio-nodeagent-{{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "nodeagent.name" . }}
    helm.sh/chart: {{ template "nodeagent.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]