apiVersion: v1
kind: List
metadata:
  name: tracing-services
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.provider }}
    helm.sh/chart: {{ template "tracing.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/name: {{ .Values.provider }}
      helm.sh/chart: {{ template "tracing.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  spec:
    type: {{ .Values.service.type }}
    ports:
      - port: {{ .Values.service.externalPort }}
        targetPort: 9411
        protocol: TCP
        name: {{ .Values.service.name }}
    selector:
      app.kubernetes.io/name: {{ .Values.provider }}
- apiVersion: v1
  kind: Service
  metadata:
    name: tracing
    namespace: {{ .Release.Namespace }}
    annotations:
      {{- range $key, $val := .Values.service.annotations }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    labels:
      app.kubernetes.io/name: {{ .Values.provider }}
      helm.sh/chart: {{ template "tracing.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  spec:
    ports:
      - name: http-query
        port: 80
        protocol: TCP
{{ if eq .Values.provider "jaeger" }}
        targetPort: 16686
{{ else }}
        targetPort: 9411
{{ end}}
    selector:
      app.kubernetes.io/name: {{ .Values.provider }}
