{{ if eq .Values.provider "jaeger" }}

apiVersion: v1
kind: List
metadata:
  name: jaeger-services
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jaeger
    helm.sh/chart: {{ template "tracing.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query
    namespace: {{ .Release.Namespace }}
    annotations:
      {{- range $key, $val := .Values.service.annotations }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    labels:
      app.kubernetes.io/name: jaeger
      jaeger-infra: jaeger-service
      helm.sh/chart: {{ template "tracing.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  spec:
    ports:
      - name: query-http
        port: 16686
        protocol: TCP
        targetPort: 16686
    selector:
      app.kubernetes.io/name: jaeger
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-collector
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/name: jaeger
      jaeger-infra: collector-service
      helm.sh/chart: {{ template "tracing.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  spec:
    ports:
    - name: jaeger-collector-tchannel
      port: 14267
      protocol: TCP
      targetPort: 14267
    - name: jaeger-collector-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    selector:
      app.kubernetes.io/name: jaeger
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-agent
    namespace: {{ .Release.Namespace }}
    labels:
      app.kubernetes.io/name: jaeger
      jaeger-infra: agent-service
      helm.sh/chart: {{ template "tracing.chart" . }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  spec:
    ports:
    - name: agent-zipkin-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: agent-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: agent-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    clusterIP: None
    selector:
      app.kubernetes.io/name: jaeger
{{ end }}

