{{- if or .Values.podDisruptionBudget .Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: certmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: certmanager
    helm.sh/chart: {{ template "certmanager.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 4 }}
    {{- end }}
spec:
{{- if .Values.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
{{- else if .Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: certmanager
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
